steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_BACKEND_BASE_URL=${_NEXT_PUBLIC_BACKEND_BASE_URL}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
