steps:
  - name: gcr.io/cloud-builders/docker
    secretEnv:
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY
    args:
      [
        "build",
        "--build-arg",
        "NODE_ENV=${_NODE_ENV}",
        "--build-arg",
        "NEXT_PUBLIC_APP_ENV=${_NEXT_PUBLIC_APP_ENV}",
        "--build-arg",
        "NEXT_TELEMETRY_DISABLED=${_NEXT_TELEMETRY_DISABLED}",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY=$$NEXT_PUBLIC_SUPABASE_ANON_KEY",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=$$NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY",
        "--build-arg",
        "NEXT_PUBLIC_BACKEND_BASE_URL=${_NEXT_PUBLIC_BACKEND_BASE_URL}",
        "-t",
        "${_IMAGE_URI}:${SHORT_SHA}",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_IMAGE_URI}:${SHORT_SHA}"
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE}",
        "--image",
        "${_IMAGE_URI}:${SHORT_SHA}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--min-instances",
        "${_MIN_INSTANCES}",
        "--max-instances",
        "${_MAX_INSTANCES}",
        "--memory",
        "${_MEMORY}",
        "--cpu",
        "${_CPU}",
        "--port",
        "${_PORT}",
        "--set-env-vars",
        "NODE_ENV=${_NODE_ENV}",
        "--set-env-vars",
        "NEXT_PUBLIC_APP_ENV=${_NEXT_PUBLIC_APP_ENV}",
        "--set-env-vars",
        "NEXT_TELEMETRY_DISABLED=${_NEXT_TELEMETRY_DISABLED}",
        "--set-env-vars",
        "NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}",
        "--set-env-vars",
        "NEXT_PUBLIC_WIZARD_URL=${_NEXT_PUBLIC_WIZARD_URL}",
        "--set-env-vars",
        "NEXT_PUBLIC_RAISE_APPRAISAL_API_URL=${_NEXT_PUBLIC_RAISE_APPRAISAL_API_URL}",
        "--set-env-vars",
        "NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}",
        "--set-env-vars",
        "NEXT_PUBLIC_BACKEND_BASE_URL=${_NEXT_PUBLIC_BACKEND_BASE_URL}",                
      ]

substitutions:
  _REGION: us-central1
  _IMAGE_URI: us-central1-docker.pkg.dev/rovs-492706/cloud-run-images/raise-appraisal-frontend
  _PORT: "8080"
  _CPU: "1"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "2"
  _MEMORY: 512Mi
  _SERVICE: raise-appraisal-fe-staging
  _NODE_ENV: staging
  _NEXT_PUBLIC_APP_ENV: staging
  _NEXT_TELEMETRY_DISABLED: "1"
  _NEXT_PUBLIC_APP_URL: https://staging.raiseappraisal.com
  _NEXT_PUBLIC_WIZARD_URL: https://staging.raiseappraisal.com
  _NEXT_PUBLIC_RAISE_APPRAISAL_API_URL: https://raise-appraisal-be-staging-402018942174.us-central1.run.app
  _NEXT_PUBLIC_SUPABASE_URL: https://tovvoeffgngoxcvjoktu.supabase.co
  _NEXT_PUBLIC_BACKEND_BASE_URL: https://raise-appraisal-be-staging-402018942174.us-central1.run.app

availableSecrets:
  secretManager:
    - versionName: projects/rovs-492706/secrets/next-public-supabase-anon-key/versions/latest
      env: NEXT_PUBLIC_SUPABASE_ANON_KEY
    - versionName: projects/rovs-492706/secrets/next-public-supabase-service-role-key/versions/latest
      env: NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY

options:
  logging: CLOUD_LOGGING_ONLY